### ISSUE TITLE
Linking error "pybuda/pybuda/_C.so: undefined symbol: _ZTIN2tt17tt_compile_resultE"

### ISSUE THREAD

**Issue by jaebaek** [tenstorrent/tt-buda#40]
I followed the instruction from https://docs.tenstorrent.com/tenstorrent/v/tt-buda/installation

After running
```
make
source  build/python_env/bin/activate
```

I got the following error:

```
Python 3.8.10 (default, Mar 25 2024, 10:42:49) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaebaek/tt-buda/pybuda/pybuda/__init__.py", line 42, in <module>
    from .module import Module, PyTorchModule, PyBudaModule, TFModule, TFGraphDefModule, OnnxModule, MXNetModule, JaxModule, TFLiteModule
  File "/home/jaebaek/tt-buda/pybuda/pybuda/module.py", line 14, in <module>
    from .pybudaglobal import register_module, lazy_trace_data
  File "/home/jaebaek/tt-buda/pybuda/pybuda/pybudaglobal.py", line 16, in <module>
    from pybuda._C.backend_api import BackendType
ImportError: /home/jaebaek/tt-buda/pybuda/pybuda/_C.so: undefined symbol: _ZTIN2tt17tt_compile_resultE
```

A few weeks ago, it worked fine. This is particularly critical because `import pybuda` does not work.

I investigated this a little bit. I confirmed that `readelf` result of **build/obj/pybuda/csrc/backend_api/backend_api.o** has the following symbol tables:

```
 1043826   5092: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN2tt27tt_compile_resu
 1043827   5093: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN2tt20tt_fw_compile_r
 1043828   5094: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN2tt17tt_compile_resu
 1043829   5095: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN2tt25tt_overlay_comp
```

while the preprocess only compile showed me the types were included correctly.

I am sure this is `virtual` function issue caused by [this line](https://github.com/tenstorrent/tt-budabackend/blob/254b13aaead3ccea8b6adc11b167c3afe0cf0494/netlist/tt_backend_api_types.hpp#L254) from budabackend.

To fix this, I updated the make files like
```
diff --git a/pybuda/csrc/backend_api/module.mk b/pybuda/csrc/backend_api/module.mk
index 04e772f..9c25296 100644
--- a/pybuda/csrc/backend_api/module.mk
+++ b/pybuda/csrc/backend_api/module.mk
@@ -9,6 +9,19 @@ BACKEND_INCLUDES =  -Ithird_party/budabackend
 
 BUDABACKEND_LIBDIR = third_party/budabackend/build/lib
 BUDABACKEND_LIB = $(BUDABACKEND_LIBDIR)/libtt.so
+BUDABACKEND_COMMON_LIB = $(BUDABACKEND_LIBDIR)/libcommon.a
+BUDABACKEND_OPS_LIB = $(BUDABACKEND_LIBDIR)/libops.a
+BUDABACKEND_GOLDEN_LIB = $(BUDABACKEND_LIBDIR)/libgolden.a
+BUDABACKEND_NETLIST_LIB = $(BUDABACKEND_LIBDIR)/libnetlist.a
+BUDABACKEND_NET2HLKS_LIB = $(BUDABACKEND_LIBDIR)/libnet2hlks.a
+BUDABACKEND_LOADER_LIB = $(BUDABACKEND_LIBDIR)/libloader.a
+BUDABACKEND_PIPEGEN2_LIB = $(BUDABACKEND_LIBDIR)/libpipegen2.a
+BUDABACKEND_RUNTIME_LIB = $(BUDABACKEND_LIBDIR)/libruntime.a
+BUDABACKEND_MODEL_LIB = $(BUDABACKEND_LIBDIR)/libmodel.a
+BUDABACKEND_COMPILE_TRISC_LIB = $(BUDABACKEND_LIBDIR)/libcompile_trisc.a
+BUDABACKEND_PERF_LIB = $(BUDABACKEND_LIBDIR)/libperf_lib.a
+BUDABACKEND_OP_MODEL_LIB = $(BUDABACKEND_LIBDIR)/libop_model.a
+BUDABACKEND_DEBUDA_SERVER_LIB = $(BUDABACKEND_LIBDIR)/libdbdserver.a
 BUDABACKEND_DEVICE = $(BUDABACKEND_LIBDIR)/libdevice.so
 BUDABACKEND_NET2PIPE = third_party/budabackend/build/bin/net2pipe
 BUDABACKEND_PIPEGEN = third_party/budabackend/build/bin/pipegen2
@@ -51,7 +64,22 @@ third_party/budabackend/src/net2pipe: $(BUDABACKEND_NET2PIPE) $(BUDABACKEND_PIPE
 # Each module has a top level target as the entrypoint which must match the subdir name
 pybuda/csrc/backend_api: $(PYBUDA_CSRC_BACKENDAPI_LIB) $(BUDABACKEND_LIB) $(BUDABACKEND_DEVICE) $(PYBUDA_CSRC_SHARED_UTILS_LIB) ;
 
-$(PYBUDA_CSRC_BACKENDAPI_LIB): $(PYBUDA_CSRC_BACKENDAPI_OBJS) $(BUDABACKEND_LIB) $(BUDABACKEND_DEVICE) $(PYBUDA_CSRC_SHARED_UTILS_LIB)
+
+
+$(PYBUDA_CSRC_BACKENDAPI_LIB): $(PYBUDA_CSRC_BACKENDAPI_OBJS) $(BUDABACKEND_DEVICE) $(PYBUDA_CSRC_SHARED_UTILS_LIB) \
+       $(BUDABACKEND_COMMON_LIB) \
+       $(BUDABACKEND_OPS_LIB) \
+       $(BUDABACKEND_GOLDEN_LIB) \
+       $(BUDABACKEND_NETLIST_LIB) \
+       $(BUDABACKEND_NET2HLKS_LIB) \
+       $(BUDABACKEND_LOADER_LIB) \
+       $(BUDABACKEND_PIPEGEN2_LIB) \
+       $(BUDABACKEND_RUNTIME_LIB) \
+       $(BUDABACKEND_MODEL_LIB) \
+       $(BUDABACKEND_COMPILE_TRISC_LIB) \
+       $(BUDABACKEND_PERF_LIB) \
+       $(BUDABACKEND_OP_MODEL_LIB) \
+       $(BUDABACKEND_DEBUDA_SERVER_LIB)
        @mkdir -p $(LIBDIR)
        ar rcs $@ $^
 
diff --git a/pybuda/csrc/module.mk b/pybuda/csrc/module.mk
index 373250f..41f8e4b 100644
--- a/pybuda/csrc/module.mk
+++ b/pybuda/csrc/module.mk
@@ -31,7 +31,7 @@ ifndef BUDABACKEND_LIBDIR
 $(error BUDABACKEND_LIBDIR not set)
 endif
 
-PYBUDA_CSRC_LDFLAGS = -Wl,-z,origin -Wl,-rpath,\$$ORIGIN/../python_env/lib/$(PYTHON_VERSION)/site-packages/torch/lib -Wl,-rpath,\$$ORIGIN/../budabackend/build/lib -Wl,-rpath,\$$ORIGIN/../../$(BUDABACKEND_LIBDIR) -lstdc++fs -lboost_serialization -ltorch -ltorch_cpu -lc10 -ltorch_python -lnet2pipe_tile_maps
+PYBUDA_CSRC_LDFLAGS = -Wl,-z,origin -Wl,-rpath,\$$ORIGIN/../python_env/lib/$(PYTHON_VERSION)/site-packages/torch/lib -lstdc++fs -lboost_serialization -ltorch -ltorch_cpu -lc10 -ltorch_python -lnet2pipe_tile_maps
 
 PYBUDA_CSRC_SRCS = \
                pybuda/csrc/pybuda_bindings.cpp \
```

I got another error:
```
Python 3.8.10 (default, Mar 25 2024, 10:42:49) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaebaek/tt-buda/pybuda/pybuda/__init__.py", line 42, in <module>
    from .module import Module, PyTorchModule, PyBudaModule, TFModule, TFGraphDefModule, OnnxModule, MXNetModule, JaxModule, TFLiteModule
  File "/home/jaebaek/tt-buda/pybuda/pybuda/module.py", line 14, in <module>
    from .pybudaglobal import register_module, lazy_trace_data
  File "/home/jaebaek/tt-buda/pybuda/pybuda/pybudaglobal.py", line 16, in <module>
    from pybuda._C.backend_api import BackendType
ImportError: /home/jaebaek/tt-buda/pybuda/pybuda/_C.so: undefined symbol: _ZTIN4YAML13BadConversionE
>>> 
```

**Comment by jaebaek** [comment]
Maybe, I guess we have the similar error e.g., `virtual` function. Maybe, we have to build them all based on only static linking because of heavy `virtual` function uses here and there.

**Comment by milank94** [comment]
Hi @jaebaek 

To build from source, follow these steps:

```sh
git clone https://github.com/tenstorrent/tt-buda.git
cd tt-buda
git submodule update --init --recursive
bash env_for_wormhole_b0.sh  # or bash env_for_grayskull.sh
source build/python_env/bin/activate
```

**Comment by jaebaek** [comment]
It works, thanks!

(the script file name seems to be `env_for_silicon.sh` instead of `env_for_grayskull.sh` :))
