### ISSUE TITLE
Smoke Test Error when Build from Source (v0.18.2)

### ISSUE THREAD

**Issue by jhlee508** [tenstorrent/tt-buda#53]
When running the [Smoke Test](https://docs.tenstorrent.com/pybuda/latest/installation.html#smoke-test) example code, it works perfectly with the [release (v0.18.2)](https://github.com/tenstorrent/tt-buda/releases/tag/v0.18.2). However, when building from [source (v0.18.2)](https://github.com/tenstorrent/tt-buda/tree/v0.18.2), the same test code results in errors. It seems to fail on finding ethernet fw version and when just using tt-smi, the firmware version shows as 6.9.0 which is fine.

Is this the expected outcome? Or have I missed something while compiling from source code?
I think this inconsistency needs investigation to ensure the source build aligns with the release version for other external developers.

### How I build and run test
```bash
git clone https://github.com/tenstorrent/tt-buda
cd tt-buda
git checkout tags/v0.18.2
git submodule update --init --recursive

export ARCH_NAME=wormhole_b0
make -j |& tee cmake.log

source build/python_env/bin/activate
python smoke_test.py
```
### Error log
```bash
2024-09-07 14:29:40.981 | INFO     | SiliconDriver   - Software version 6.0.0, Ethernet FW version 0.0.187 (Device 0)
2024-09-07 14:29:40.981 | FATAL    | Always          - SW/FW major version number out of sync
2024-09-07 14:29:41.000 | ERROR    | Always          - SW/FW major version number out of sync
backtrace:
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/../../third_party/budabackend/build/lib/libdevice.so(+0x3c08d) [0x7ff9f196e08d]
 --- tt_SiliconDevice::verify_eth_fw()
 --- tt_SiliconDevice::start_device(tt_device_params const&)
 --- tt_cluster::start_device(tt_device_params const&)
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/../../third_party/budabackend/build/lib/libtt.so(+0x7771e0) [0x7ff9f21b81e0]
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6df4) [0x7ffb70681df4]
 --- /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7ffb88ef2609]
 --- /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7ffb8902c353]
2024-09-07 14:29:41.001 | FATAL    | Always          - Attempting to read device aiclk when cluster device state is set to idle
2024-09-07 14:29:41.005 | ERROR    | Always          - Attempting to read device aiclk when cluster device state is set to idle
backtrace:
 --- tt_cluster::get_all_device_aiclks()
 --- tt_runtime::query_all_device_aiclks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
 --- tt_runtime::finish()
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/_C.so(+0x8b0b9f) [0x7ff9f2de9b9f]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/_C.so(+0x2aef86) [0x7ff9f27e7f86]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(PyCFunction_Call+0x59) [0x5f58f9]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyObject_MakeTpCall+0x29e) [0x5f64ce]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3() [0x50b4b3]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x5777) [0x570b67]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x1b6) [0x5f5ca6]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x907) [0x56bcf7]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalCodeWithName+0x26a) [0x569dfa]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x393) [0x5f5e83]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3() [0x59c27e]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyObject_MakeTpCall+0x1ff) [0x5f642f]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x59ad) [0x570d9d]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalCodeWithName+0x26a) [0x569dfa]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x393) [0x5f5e83]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x907) [0x56bcf7]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x1b6) [0x5f5ca6]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x907) [0x56bcf7]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x1b6) [0x5f5ca6]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3() [0x50ad5c]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(PyObject_Call+0x62) [0x5f5072]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x1f2d) [0x56d31d]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x1b6) [0x5f5ca6]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x907) [0x56bcf7]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalCodeWithName+0x26a) [0x569dfa]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x393) [0x5f5e83]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x907) [0x56bcf7]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x1b6) [0x5f5ca6]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x725) [0x56bb15]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalCodeWithName+0x26a) [0x569dfa]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyFunction_Vectorcall+0x393) [0x5f5e83]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalFrameDefault+0x1905) [0x56ccf5]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_PyEval_EvalCodeWithName+0x26a) [0x569dfa]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(PyEval_EvalCode+0x27) [0x68ce77]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3() [0x67e631]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3() [0x67e6af]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(PyRun_StringFlags+0x7f) [0x67e7ff]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(PyRun_SimpleStringFlags+0x3f) [0x67f20f]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(Py_RunMain+0x2cc) [0x6b687c]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(Py_BytesMain+0x2d) [0x6b6b4d]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffb88f31083]
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/build/python_env/bin/python3(_start+0x2e) [0x5fa81e]
2024-09-07 14:29:41.005 | INFO     | Debuda          - Debug server ended on
2024-09-07 14:29:41.008 | ERROR    | pybuda.backend:log_compile_errors:118 - Backend compile failed with error type: BackendCompileFailure.Invalid, error message: SW/FW major version number out of sync
backtrace:
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/../../third_party/budabackend/build/lib/libdevice.so(+0x3c08d) [0x7ff9f196e08d]
 --- tt_SiliconDevice::verify_eth_fw()
 --- tt_SiliconDevice::start_device(tt_device_params const&)
 --- tt_cluster::start_device(tt_device_params const&)
 --- /home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/../../third_party/budabackend/build/lib/libtt.so(+0x7771e0) [0x7ff9f21b81e0]
 --- /lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6df4) [0x7ffb70681df4]
 --- /lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7ffb88ef2609]
 --- /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7ffb8902c353]
2024-09-07 14:29:41.014 | ERROR    | pybuda.device:run_next_command:469 - Compile error: Backend compile failed!
Traceback (most recent call last):
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/ttdevice.py", line 832, in compile_for
    self.backend_api = BackendAPI(
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/backend.py", line 87, in __init__
    raise BackendCompileException(self.compile_result)
pybuda.backend.BackendCompileException: <pybuda._C.backend_api.BackendCompileResult object at 0x7ffa8b342370>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/device.py", line 458, in run_next_command
    ret = self.compile_for(
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/ttdevice.py", line 858, in compile_for
    raise RuntimeError("Backend compile failed!")
RuntimeError: Backend compile failed!
Traceback (most recent call last):
  File "smoke-test/smoke_test.py", line 35, in <module>
    test_module_direct_pytorch()
  File "smoke-test/smoke_test.py", line 30, in test_module_direct_pytorch
    output = pybuda.PyTorchModule("direct_pt", PyTorchTestModule()).run(input1, input2)
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/module.py", line 95, in run
    output_q = pybuda.run_inference(self, inputs=[args])
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/run/api.py", line 90, in run_inference
    return _run_inference(module, inputs, input_count, output_queue, _sequential, _perf_trace, _verify_cfg)
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/run/impl.py", line 277, in _run_inference
    return _run_devices_inference(
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/run/impl.py", line 467, in _run_devices_inference
    output_queue = _initialize_pipeline(False, output_queue, sequential=sequential, verify_cfg=verify_cfg)
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/run/impl.py", line 414, in _initialize_pipeline
    _compile_devices(sequential, training=training, sample_inputs=sample_inputs, sample_targets=sample_targets, microbatch_count=microbatch_count, verify_cfg=verify_cfg)
  File "/home/n4/jaehwan/research/tenstorrent/pybuda/tt-buda/pybuda/pybuda/run/impl.py", line 1252, in _compile_devices
    raise ret
RuntimeError: Backend compile failed!
2024-09-07 14:29:41.021 | DEBUG    | pybuda.run.impl:_shutdown:1269 - PyBuda shutdown
```

**Comment by milank94** [comment]
@jhlee508 I would recommend that you try doing the build with the provided bash file: https://github.com/tenstorrent/tt-buda/blob/main/env_for_wormhole_b0.sh

**Comment by jhlee508** [comment]
Now this works fine! Thanks.
